import { useState, type FormEvent } from "react";
import { Navigate } from "react-router-dom";
import type { User } from "./types";
import MtGroupsManager from "./MtGroupsManager";

type Discipline = { id: string; number: number; code: string; description: string };
type MtGroup = { id: string; number: number; name: string; site: string; canClose: boolean };

const DISCIPLINE_KEY = "eptw-disciplines:v1";
const GROUP_KEY = "eptw-mt-groups:v1";
const disciplineSeeds: Discipline[] = [
  "MFG WET", "MFG PROCUREMENT", "MFG PHOTO", "MFG IMPLANT", "MFG DRY ETCH", "MFG DIFFUSION", "MFG CVD/PD", "MFG CMP/PC", "METRO", "MATERIAL HANDLING", "IT", "FAC UPW & WWTP/EXYTE", "FAC UPW & WWTP",
].map((code, index) => ({ id: `discipline-${index + 21}`, number: index + 21, code, description: code }));
const groupNames = ["F10A1 AMHS Engineer", "F10A1 AMHS Manager", "F10A1 Building Services Engineer", "F10A1 Building Services Manager", "F10A1 Chemical Gas Manager", "F10A1 Control Manager", "F10A1 Electrical Engineer/Technician", "F10A1 Electrical Manager", "F10A1 Equipment Engineer", "F10A1 Equipment Manager", "F10A1 Facilities SIPP Coordinators", "F10A1 Mechanical Senior Manager", "F10A1 PEE Dry Engineer/Technician"];
const groupSeeds: MtGroup[] = groupNames.map((name, index) => ({ id: `group-${index + 1}`, number: index + 1, name, site: "F10A1", canClose: index === 10 }));

function readLocal<T>(key: string, seeds: T[]): T[] { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T[] : seeds; } catch { return seeds; } }
function saveLocal<T>(key: string, value: T[], setter: (items: T[]) => void) { localStorage.setItem(key, JSON.stringify(value)); setter(value); }
function Header({ title, text, onAdd }: { title: string; text: string; onAdd: () => void }) { return <header className="page-header"><div><span className="eyebrow">System management</span><h1>{title}</h1><p>{text}</p></div><button className="button primary" onClick={onAdd}>＋ Add {title === "Disciplines" ? "discipline" : "MT Group"}</button></header>; }
function DirectoryMenu({ label }: { label: string }) { return <details className="row-menu"><summary aria-label={`Actions for ${label}`}>⋯</summary><div className="row-menu-panel"><button><span className="directory-menu-icon">◉</span><span>View</span></button><button><span className="directory-menu-icon">✎</span><span>Edit</span></button></div></details>; }

export function DisciplinesPage({ user }: { user: User }) {
  const [items, setItems] = useState(() => readLocal(DISCIPLINE_KEY, disciplineSeeds)); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [form, setForm] = useState({ code: "", description: "" });
  if (!["SUPER_ADMIN", "USER_ADMIN"].includes(user.role)) return <Navigate to="/dashboard" replace />;
  const visible = items.filter((item) => `${item.code} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.code.trim() || !form.description.trim()) return; const next = [...items, { id: crypto.randomUUID(), number: Math.max(0, ...items.map((item) => item.number)) + 1, code: form.code.trim().toUpperCase(), description: form.description.trim() }]; saveLocal(DISCIPLINE_KEY, next, setItems); setForm({ code: "", description: "" }); setAdding(false); };
  return <div className="page directory-page"><Header title="Disciplines" text="Manage permit disciplines and their descriptions." onAdd={() => setAdding(true)} /><section className="card directory-card"><div className="directory-toolbar"><label className="search"><span>⌕</span><input aria-label="Search disciplines" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search discipline code or description" /></label><span className="result-count">{visible.length} disciplines</span></div>{adding && <form className="directory-form" onSubmit={submit}><label>Discipline code<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label>Description<input required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div><button type="button" className="button ghost" onClick={() => setAdding(false)}>Cancel</button><button className="button primary">Save discipline</button></div></form>}<div className="directory-table-wrap"><table className="directory-table disciplines-table"><thead><tr><th>#</th><th>Discipline Code</th><th>Description</th><th>Action</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.number}</td><td><strong>{item.code}</strong></td><td>{item.description}</td><td><DirectoryMenu label={item.code} /></td></tr>)}</tbody></table></div></section></div>;
}

function LegacyMtGroupsPage({ user }: { user: User }) {
  const [items, setItems] = useState(() => readLocal(GROUP_KEY, groupSeeds)); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: "", site: "F10A1", canClose: false }); const [ascending, setAscending] = useState(true);
  if (!["SUPER_ADMIN", "USER_ADMIN"].includes(user.role)) return <Navigate to="/dashboard" replace />;
  const visible = items.filter((item) => `${item.name} ${item.site}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (ascending ? 1 : -1) * a.name.localeCompare(b.name));
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.site.trim()) return; const next = [...items, { id: crypto.randomUUID(), number: Math.max(0, ...items.map((item) => item.number)) + 1, name: form.name.trim(), site: form.site.trim().toUpperCase(), canClose: form.canClose }]; saveLocal(GROUP_KEY, next, setItems); setForm({ name: "", site: "F10A1", canClose: false }); setAdding(false); };
  return <div className="page directory-page"><Header title="MT Groups" text="Manage reviewer groups, site ownership, and closure authority." onAdd={() => setAdding(true)} /><section className="card directory-card"><div className="directory-toolbar"><label className="search"><span>⌕</span><input aria-label="Search MT Groups" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search group name or site" /></label><span className="result-count">{visible.length} groups</span></div>{adding && <form className="directory-form group-form" onSubmit={submit}><label>Group name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Site code<input required value={form.site} onChange={(event) => setForm({ ...form, site: event.target.value })} /></label><label className="directory-check"><input type="checkbox" checked={form.canClose} onChange={(event) => setForm({ ...form, canClose: event.target.checked })} /> Can close permits</label><div><button type="button" className="button ghost" onClick={() => setAdding(false)}>Cancel</button><button className="button primary">Save MT Group</button></div></form>}<div className="directory-table-wrap"><table className="directory-table groups-table"><thead><tr><th>#</th><th><button onClick={() => setAscending(!ascending)}>Group Name <span>{ascending ? "↑" : "↓"}</span></button></th><th>Site</th><th>Can close permits?</th><th>Action</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{item.number}</td><td><strong>{item.name}</strong></td><td>{item.site}</td><td><span className={`yes-no ${item.canClose ? "yes" : ""}`}>{item.canClose ? "Yes" : "No"}</span></td><td><DirectoryMenu label={item.name} /></td></tr>)}</tbody></table></div></section></div>;
}
export function MtGroupsPage({ user }: { user: User }) { return <MtGroupsManager user={user} />; }
void LegacyMtGroupsPage;
