import { useState, type FormEvent } from "react";
import { Navigate } from "react-router-dom";
import { DISCIPLINES } from "./constants";
import type { User } from "./types";

type Kind = "PARENT" | "CHILD";
type FieldType = "TEXT" | "TEXTAREA" | "NUMBER" | "DATE" | "CHECKBOX" | "SELECT";
type Field = { id: string; label: string; type: FieldType; required: boolean; options?: string[] };
type Section = { id: string; title: string; description: string; fields: Field[] };
type Template = { id: string; kind: Kind; name: string; code: string; discipline: string; description: string; active: boolean; updatedAt: string; sections?: Section[] };
const storageKey = "eptw-templates:v1";
const seeds: Template[] = [
  { id: "tpl-parent-general", kind: "PARENT", name: "General Permit to Work", code: "G", discipline: "AMHS", description: "Standard parent permit for controlled maintenance and installation work.", active: true, updatedAt: "2026-09-08T08:00:00.000Z" },
  { id: "tpl-parent-facilities", kind: "PARENT", name: "Facilities Maintenance Permit", code: "FM", discipline: "Facilities", description: "Parent permit for building and utility maintenance activities.", active: true, updatedAt: "2026-09-08T08:00:00.000Z" },
  { id: "tpl-child-hotwork", kind: "CHILD", name: "Hot Work Permit", code: "HW", discipline: "Facilities", description: "Mandatory child permit for welding, cutting, grinding, and ignition sources.", active: true, updatedAt: "2026-09-08T08:00:00.000Z" },
];
const read = () => { try { const value = localStorage.getItem(storageKey); return value ? JSON.parse(value) as Template[] : seeds; } catch { return seeds; } };
const newSection = (): Section => ({ id: crypto.randomUUID(), title: "General information", description: "", fields: [{ id: crypto.randomUUID(), label: "Equipment / system reference", type: "TEXT", required: true }] });

export default function TemplateBuilderPage({ user }: { user: User }) {
  const [items, setItems] = useState(read); const [kind, setKind] = useState<Kind>("PARENT"); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false); const [sections, setSections] = useState<Section[]>([newSection()]);
  const [form, setForm] = useState({ name: "", code: "", discipline: DISCIPLINES[0], description: "" });
  if (!["SUPER_ADMIN", "USER_ADMIN"].includes(user.role)) return <Navigate to="/dashboard" replace />;
  const visible = items.filter((item) => item.kind === kind && `${item.name} ${item.code} ${item.discipline}`.toLowerCase().includes(query.toLowerCase()));
  const save = (next: Template[]) => { setItems(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const updateSection = (id: string, change: Partial<Section>) => setSections(sections.map((section) => section.id === id ? { ...section, ...change } : section));
  const updateField = (sectionId: string, fieldId: string, change: Partial<Field>) => setSections(sections.map((section) => section.id === sectionId ? { ...section, fields: section.fields.map((field) => field.id === fieldId ? { ...field, ...change } : field) } : section));
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.code.trim() || !form.description.trim()) return; save([{ id: crypto.randomUUID(), kind, ...form, name: form.name.trim(), code: form.code.trim().toUpperCase(), sections, active: true, updatedAt: new Date().toISOString() }, ...items]); setAdding(false); setForm({ name: "", code: "", discipline: DISCIPLINES[0], description: "" }); setSections([newSection()]); };
  const changeKind = (next: Kind) => { setKind(next); setAdding(false); };

  return <div className="page template-page">
    <header className="page-header"><div><span className="eyebrow">System management</span><h1>Permit templates</h1><p>Create reusable permit forms with configurable sections and elements.</p></div><button className="button primary" onClick={() => setAdding(true)}>+ Add {kind === "PARENT" ? "parent" : "child"} template</button></header>
    <section className="card template-workspace">
      <div className="template-tabs" role="tablist" aria-label="Template types"><button role="tab" aria-selected={kind === "PARENT"} className={kind === "PARENT" ? "active" : ""} onClick={() => changeKind("PARENT")}>Parent Template <b>{items.filter((item) => item.kind === "PARENT").length}</b></button><button role="tab" aria-selected={kind === "CHILD"} className={kind === "CHILD" ? "active" : ""} onClick={() => changeKind("CHILD")}>Child Template <b>{items.filter((item) => item.kind === "CHILD").length}</b></button></div>
      <div className="template-toolbar"><label className="search"><span>⌕</span><input aria-label="Search templates" placeholder="Search template name, code or discipline" value={query} onChange={(event) => setQuery(event.target.value)} /></label><span className="result-count">{visible.length} templates</span></div>
      {adding && <form className="template-builder-form" onSubmit={submit}>
        <div className="builder-meta"><label>Template name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Template code<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label>Discipline<select value={form.discipline} onChange={(event) => setForm({ ...form, discipline: event.target.value })}>{DISCIPLINES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Description<textarea required rows={2} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div>
        <div className="builder-title"><div><h3>Form sections</h3><p>Build the fields users complete when this template is selected.</p></div><button type="button" className="button ghost small" onClick={() => setSections([...sections, newSection()])}>+ Add section</button></div>
        {sections.map((section, sectionIndex) => <section className="builder-section" key={section.id}><div className="builder-section-head"><b>{sectionIndex + 1}</b><input required aria-label={`Section ${sectionIndex + 1} title`} value={section.title} onChange={(event) => updateSection(section.id, { title: event.target.value })} /><button type="button" disabled={sections.length === 1} onClick={() => setSections(sections.filter((item) => item.id !== section.id))}>×</button></div><input className="section-description" placeholder="Section instructions (optional)" value={section.description} onChange={(event) => updateSection(section.id, { description: event.target.value })} /><div className="builder-fields">{section.fields.map((field, index) => <div className="builder-field" key={field.id}><span>{index + 1}</span><input required aria-label="Field label" placeholder="Field label" value={field.label} onChange={(event) => updateField(section.id, field.id, { label: event.target.value })} /><select aria-label="Field type" value={field.type} onChange={(event) => updateField(section.id, field.id, { type: event.target.value as FieldType })}>{[["TEXT", "Short text"], ["TEXTAREA", "Long text"], ["NUMBER", "Number"], ["DATE", "Date"], ["CHECKBOX", "Checkbox"], ["SELECT", "Dropdown"]].map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select>{field.type === "SELECT" && <input aria-label="Dropdown choices" placeholder="Choices separated by commas" value={field.options?.join(", ") ?? ""} onChange={(event) => updateField(section.id, field.id, { options: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} />}<label className="required-toggle"><input type="checkbox" checked={field.required} onChange={(event) => updateField(section.id, field.id, { required: event.target.checked })} /> Required</label><button type="button" onClick={() => updateSection(section.id, { fields: section.fields.filter((item) => item.id !== field.id) })}>×</button></div>)}</div><button type="button" className="add-field-button" onClick={() => updateSection(section.id, { fields: [...section.fields, { id: crypto.randomUUID(), label: "", type: "TEXT", required: false }] })}>+ Add form element</button></section>)}
        <div className="builder-actions"><button type="button" className="button ghost" onClick={() => setAdding(false)}>Cancel</button><button className="button primary">Save {kind === "PARENT" ? "parent" : "child"} template</button></div>
      </form>}
      <table className="template-table"><thead><tr><th>Template name</th><th>Code</th><th>Discipline</th><th>Description</th><th>Form</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map((template) => <tr key={template.id}><td><div className={`template-kind-icon ${template.kind.toLowerCase()}`}>{template.kind[0]}</div><strong>{template.name}</strong></td><td><b className="template-code">{template.code}</b></td><td>{template.discipline}</td><td>{template.description}</td><td>{template.sections?.length ?? 0} sections<br /><small>{template.sections?.reduce((count, section) => count + section.fields.length, 0) ?? 0} elements</small></td><td><span className={`template-status ${template.active ? "enabled" : ""}`}>{template.active ? "Active" : "Inactive"}</span></td><td><details className="row-menu"><summary aria-label={`Actions for ${template.name}`}>&hellip;</summary><div className="row-menu-panel"><button onClick={() => save(items.map((item) => item.id === template.id ? { ...item, active: !item.active } : item))}>Set {template.active ? "inactive" : "active"}</button><button onClick={() => save([{ ...template, id: crypto.randomUUID(), name: `Copy of ${template.name}` }, ...items])}>Duplicate</button></div></details></td></tr>)}</tbody></table>
    </section>
  </div>;
}
