import { useState, type FormEvent, type PointerEvent as ReactPointerEvent } from "react";
import { Link, Navigate, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { DISCIPLINES } from "./constants";
import type { User } from "./types";
import { requiresSpecification } from "./templateOptions";
import SectionPermissionSummary from "./SectionPermissionSummary";
import { readGroups } from "./groupStore";
import type { SectionEditAccess } from "./sectionAccess";

type Kind = "PARENT" | "CHILD";
type FieldType = "TEXT" | "TEXTAREA" | "RADIO" | "CHECKBOX" | "MULTI_CHECKBOX" | "DATE" | "TIME" | "DATE_RANGE" | "SELECT" | "FILE" | "SIGNATURE" | "FREE_TEXT" | "MAP" | "REVIEWER_LIST" | "NUMBER";
const fieldTypes: [FieldType, string][] = [["TEXT", "Text"], ["TEXTAREA", "Textarea"], ["RADIO", "Radio"], ["CHECKBOX", "Checkbox"], ["MULTI_CHECKBOX", "Multiple Checkbox"], ["DATE", "Date"], ["TIME", "Time"], ["DATE_RANGE", "Date Range"], ["SELECT", "Select"], ["FILE", "File"], ["SIGNATURE", "eSignature"], ["FREE_TEXT", "Free Text"], ["MAP", "Map"], ["REVIEWER_LIST", "Reviewer List"], ["NUMBER", "Number"]];
type FieldWidth = 1 | 2 | 3 | 4 | 5 | 6;
type Field = { id: string; label: string; type: FieldType; required: boolean; options?: string[]; specifyOptions?: (boolean | null)[]; childTemplateIds?: (string | null)[]; tabId?: string; width?: FieldWidth; height?: number };
type SectionTab = { id: string; label: string };
type Section = { id: string; title: string; description: string; fields: Field[]; tabs?: SectionTab[]; editAccess?: SectionEditAccess };
type Template = { id: string; kind: Kind; name: string; code: string; discipline: string; description: string; active: boolean; draft?: boolean; updatedAt: string; sections?: Section[] };
const storageKey = "eptw-templates:v4";
const seeds: Template[] = [
  { id: "tpl-parent-general", kind: "PARENT", name: "General", code: "G", discipline: "AMHS", description: "General permit for controlled work.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-parent-tool-install", kind: "PARENT", name: "Tool Install", code: "TI", discipline: "AMHS", description: "Permit for tool installation work.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-parent-sipp", kind: "PARENT", name: "SIPP", code: "GS", discipline: "Facilities", description: "Permit for SIPP controlled work.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a01", kind: "CHILD", name: "Upload Risk Assessment Form", code: "A01", discipline: "Facilities", description: "Upload the applicable risk assessment form.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a02", kind: "CHILD", name: "Upload Schedule, Work Layout, Traffic Control Plan, Emergency Response Procedure, Escalation Plan", code: "A02", discipline: "Facilities", description: "Upload the supporting work plans and emergency procedures.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a03", kind: "CHILD", name: "Uploads for 3D Works", code: "A03", discipline: "Facilities", description: "Upload supporting documents for 3D works.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a04", kind: "CHILD", name: "For gases, initial tool power up of tool", code: "A04", discipline: "Facilities", description: "Controls for gases and initial tool power-up.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a05", kind: "CHILD", name: "Ladder Certification99", code: "A05", discipline: "Facilities", description: "Ladder certification requirement.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a06", kind: "CHILD", name: "Material Lifter/Lifting Equipment, lifting of Pressure Vessel/Air Compressor within MICRON existing building or Operation.", code: "A06", discipline: "Facilities", description: "Controls for material lifting and lifting equipment.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a07", kind: "CHILD", name: "Proposed use of explosive powered tool/Projectiles Tools Such as Nail Gun or Stapler Gun #A7", code: "A07", discipline: "Facilities", description: "Controls for explosive-powered or projectile tools.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a08", kind: "CHILD", name: "Proposed Excavation works. #A8", code: "A08", discipline: "Facilities", description: "Controls for proposed excavation works.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a09", kind: "CHILD", name: "Constructing Scaffolding Checklist", code: "A09", discipline: "Facilities", description: "Checklist for scaffold construction.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a10", kind: "CHILD", name: "Upload RMF Pre-Entry Checklist", code: "A10", discipline: "Facilities", description: "Upload the RMF pre-entry checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a11", kind: "CHILD", name: "Upload Self-Retractable Lanyard or Device (SRL/SRD) Record List", code: "A11", discipline: "Facilities", description: "Upload the SRL/SRD record list.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b1", kind: "CHILD", name: "HOT WORKS", code: "B1", discipline: "Facilities", description: "Daily hot-work permit controls.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b2", kind: "CHILD", name: "CONFINED SPACE", code: "B2", discipline: "Facilities", description: "Confined-space permit controls.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b3", kind: "CHILD", name: "LIFTING", code: "B3", discipline: "Facilities", description: "Lifting permit controls.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b4", kind: "CHILD", name: "WORK AT HEIGHT", code: "B4", discipline: "Facilities", description: "Work-at-height permit controls.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b5", kind: "CHILD", name: "LSS IMPAIRMENT PERMIT", code: "B5", discipline: "Facilities", description: "Life-safety-system impairment controls.", active: false, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b6", kind: "CHILD", name: "LIVE ELECTRICAL PERMIT", code: "B6", discipline: "Facilities", description: "Live electrical work controls.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-c1", kind: "CHILD", name: "FAB 10 Environmental Aspect/Impact Assessment", code: "C1", discipline: "Facilities", description: "Environmental aspect and impact assessment.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-01-a", kind: "CHILD", name: "A Frame Ladder Inspection", code: "01 - (A)", discipline: "Facilities", description: "A-frame ladder inspection checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-04-a", kind: "CHILD", name: "Scaffold Constructing Checklist", code: "04 - (A)", discipline: "Facilities", description: "Scaffold construction checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a12", kind: "CHILD", name: "Proposed use of Personnel Lift/MEWP", code: "A12", discipline: "Facilities", description: "Controls for personnel lifts and mobile elevating work platforms.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-a13", kind: "CHILD", name: "Demolition Work", code: "A13", discipline: "Facilities", description: "Controls for demolition work.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-b8", kind: "CHILD", name: "Dirty Permit", code: "B8", discipline: "Facilities", description: "Controls for dirty work.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-01-b", kind: "CHILD", name: "Platform Ladder Checklist", code: "01 - (B)", discipline: "Facilities", description: "Platform ladder inspection checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-01-c", kind: "CHILD", name: "Tool Ladder Checklist", code: "01 - (C)", discipline: "Facilities", description: "Tool ladder inspection checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-01-d", kind: "CHILD", name: "Fixed Ladder Checklist", code: "01 - (D)", discipline: "Facilities", description: "Fixed ladder inspection checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-01-e", kind: "CHILD", name: "Extension Ladder Checklist", code: "01 - (E)", discipline: "Facilities", description: "Extension ladder inspection checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-04-b", kind: "CHILD", name: "Scaffold In-use Checklist", code: "04 - (B)", discipline: "Facilities", description: "Scaffold in-use checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
  { id: "tpl-child-04-c", kind: "CHILD", name: "Scaffold Dismantle Checklist", code: "04 - (C)", discipline: "Facilities", description: "Scaffold dismantling checklist.", active: true, updatedAt: "2026-10-01T00:00:00.000Z" },
];
const read = () => { try { const value = localStorage.getItem(storageKey); return value ? JSON.parse(value) as Template[] : seeds; } catch { return seeds; } };
const newSection = (): Section => ({ id: crypto.randomUUID(), title: "General information", description: "", fields: [{ id: crypto.randomUUID(), label: "Equipment / system reference", type: "TEXT", required: true, width: 3 }] });
const TemplateActionIcon = ({ name }: { name: "view" | "edit" | "delete" }) => name === "view"
  ? <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.75"/></svg>
  : name === "edit"
    ? <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 20 4.2-1 10.6-10.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/><path d="m14.5 6.7 2.8 2.8"/></svg>
    : <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>;
const FieldActionIcon = ({ name }: { name: "drag" | "edit" }) => name === "drag"
  ? <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2v20M2 12h20M8 6l4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4"/></svg>
  : <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 20 4.2-1 10.6-10.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/><path d="m14.5 6.7 2.8 2.8"/></svg>;

function ChildTemplatePicker({ optionIndex, templateId, templates, onChange }: { optionIndex: number; templateId?: string | null; templates: Template[]; onChange: (templateId: string | null, template?: Template) => void }) {
  const [open, setOpen] = useState(false);
  const attached = templates.find((template) => template.id === templateId);
  return <div className={`child-template-picker ${attached ? "attached" : ""}`}><button type="button" aria-label={`Attach child template to checkbox option ${optionIndex + 1}`} aria-expanded={open} title={attached ? `Attached: ${attached.name}` : "Attach child template"} onClick={() => setOpen(!open)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10.5 13.5 14 10a3 3 0 1 1 4.2 4.2l-5.3 5.3a5 5 0 0 1-7.1-7.1l6-6a3.5 3.5 0 0 1 5 5l-6 6a2 2 0 0 1-2.8-2.8l5.3-5.3"/></svg>{attached && <i aria-hidden="true" />}</button>{open && <div className="child-template-picker-panel"><label><span>Attached child template</span><select aria-label={`Child template for checkbox option ${optionIndex + 1}`} value={templateId ?? ""} onChange={(event) => { const selected = templates.find((template) => template.id === event.target.value); onChange(event.target.value || null, selected); setOpen(false); }}><option value="">No child template</option>{templates.map((template) => <option value={template.id} key={template.id}>{template.code} · {template.name}</option>)}</select></label>{attached && <button type="button" onClick={() => { onChange(null); setOpen(false); }}>Remove attachment</button>}</div>}</div>;
}

function BuilderFieldCard({ field, childTemplates, index, count, dragging, onChange, onMove, onRemove, onDragStart, onDrop }: { field: Field; childTemplates: Template[]; index: number; count: number; dragging: boolean; onChange: (change: Partial<Field>) => void; onMove: (direction: -1 | 1) => void; onRemove: () => void; onDragStart: () => void; onDrop: () => void }) {
  const width = field.width ?? (field.type === "TEXTAREA" ? 6 : 3);
  const label = field.label || `Field ${index + 1}`;
  const checkboxOptions = field.options?.length ? field.options : [field.label || "Checkbox 1"];
  const selectOptions = field.options?.length ? field.options : ["Option 1"];
  const beginResize = (event: ReactPointerEvent<HTMLButtonElement>) => { event.preventDefault(); event.stopPropagation(); const card = event.currentTarget.closest("article"); const canvas = card?.parentElement; if (!card || !canvas) return; const startX = event.clientX; const startWidth = width; const columnWidth = canvas.getBoundingClientRect().width / 6; const move = (pointer: PointerEvent) => onChange({ width: Math.max(1, Math.min(6, Math.round(startWidth + (pointer.clientX - startX) / columnWidth))) as FieldWidth }); const stop = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", stop); };
  const choiceType = field.type === "SELECT" || field.type === "RADIO" || field.type === "MULTI_CHECKBOX";
  const otherOptionIndex = selectOptions.findIndex((option, index) => field.specifyOptions?.[index] ?? requiresSpecification(option));
  const toggleOtherOption = (enabled: boolean) => {
    if (enabled && otherOptionIndex < 0) onChange({ options: [...selectOptions, "Others (Please Specify)"], specifyOptions: [...selectOptions.map(() => false), true], childTemplateIds: [...selectOptions.map((_, index) => field.childTemplateIds?.[index] ?? null), null] });
    if (!enabled && otherOptionIndex >= 0) onChange({ options: selectOptions.filter((_, index) => index !== otherOptionIndex), specifyOptions: selectOptions.filter((_, index) => index !== otherOptionIndex).map(() => false), childTemplateIds: selectOptions.flatMap((_, index) => index === otherOptionIndex ? [] : [field.childTemplateIds?.[index] ?? null]) });
  };
  const choicesEditor = choiceType ? <div className="settings-choice-editor">
    <b>{field.type === "SELECT" ? "Select options" : field.type === "RADIO" ? "Radio options" : "Checkboxes"}</b>
    <div className="builder-select-options">{selectOptions.map((option, optionIndex) => <div className={`builder-select-option ${field.type === "MULTI_CHECKBOX" ? "with-child-template" : ""}`} key={optionIndex}>
      <span>{optionIndex + 1}</span>
      <div className="builder-option-name">{field.type === "MULTI_CHECKBOX" && field.childTemplateIds?.[optionIndex] && <b>#{childTemplates.find((template) => template.id === field.childTemplateIds?.[optionIndex])?.code}</b>}<input aria-label={`${field.type === "SELECT" ? "Dropdown" : field.type === "RADIO" ? "Radio" : "Checkbox"} option ${optionIndex + 1}`} value={option} placeholder={`Option ${optionIndex + 1}`} onChange={(event) => onChange({ options: selectOptions.map((item, itemIndex) => itemIndex === optionIndex ? event.target.value : item) })} /></div>
      {field.type === "MULTI_CHECKBOX" && <ChildTemplatePicker optionIndex={optionIndex} templateId={field.childTemplateIds?.[optionIndex]} templates={childTemplates} onChange={(templateId, template) => { const childTemplateIds = selectOptions.map((_, itemIndex) => field.childTemplateIds?.[itemIndex] ?? null); childTemplateIds[optionIndex] = templateId; onChange({ childTemplateIds, options: template ? selectOptions.map((item, itemIndex) => itemIndex === optionIndex ? template.name : item) : selectOptions }); }} />}
      <button type="button" aria-label={`Remove option ${optionIndex + 1}`} disabled={selectOptions.length === 1} onClick={() => onChange({ options: selectOptions.filter((_, itemIndex) => itemIndex !== optionIndex), specifyOptions: field.specifyOptions?.filter((_, itemIndex) => itemIndex !== optionIndex), childTemplateIds: field.childTemplateIds?.filter((_, itemIndex) => itemIndex !== optionIndex) })}>×</button>
    </div>)}<button type="button" className="add-select-option" onClick={() => onChange({ options: [...selectOptions, `Option ${selectOptions.length + 1}`], childTemplateIds: field.type === "MULTI_CHECKBOX" ? [...(field.childTemplateIds ?? selectOptions.map(() => null)), null] : field.childTemplateIds })}>+ Add option</button></div>
    {field.type === "MULTI_CHECKBOX" && <small className="child-template-help">Use the attachment icon to link a child template to each checkbox.</small>}
    {field.type === "MULTI_CHECKBOX" && <label className="include-other-option"><input type="checkbox" checked={otherOptionIndex >= 0} onChange={(event) => toggleOtherOption(event.target.checked)} />Include Others (Please Specify)</label>}
  </div> : field.type === "CHECKBOX" ? <div className="settings-choice-editor"><b>Checkbox label</b><input aria-label="Checkbox label" value={checkboxOptions[0]} onChange={(event) => onChange({ options: [event.target.value] })} /></div> : null;
  const preview = (() => { switch (field.type) { case "TEXTAREA": return <textarea rows={3} disabled placeholder={label} />; case "SELECT": return <select disabled defaultValue=""><option value="">Select an option</option>{selectOptions.filter((option) => option.trim()).map((option, optionIndex) => <option key={optionIndex}>{option}</option>)}</select>; case "RADIO": return <div className="builder-choice-preview">{selectOptions.map((option, optionIndex) => <label key={optionIndex}><input type="radio" disabled /><span>{option}</span></label>)}</div>; case "MULTI_CHECKBOX": return <div className="builder-choice-preview">{selectOptions.map((option, optionIndex) => { const child = childTemplates.find((template) => template.id === field.childTemplateIds?.[optionIndex]); return <label key={optionIndex}><input type="checkbox" disabled /><span>{child && <b className="builder-option-code">#{child.code}</b>}<strong>{option}</strong></span>{(field.specifyOptions?.[optionIndex] ?? requiresSpecification(option)) && <input className="builder-specify-preview" disabled placeholder="Please specify when selected" />}</label>; })}</div>; case "CHECKBOX": return <label><input type="checkbox" disabled /><span>{checkboxOptions[0]}</span></label>; case "DATE_RANGE": return <div className="builder-date-range"><input type="date" disabled /><span>to</span><input type="date" disabled /></div>; case "FILE": return <input type="file" disabled />; case "SIGNATURE": return <div className="builder-placeholder-preview">Sign here</div>; case "FREE_TEXT": return <p className="builder-free-text">{field.label || "Informational text"}</p>; case "MAP": return <div className="builder-placeholder-preview">Map location</div>; case "REVIEWER_LIST": return <select disabled><option>Select a reviewer</option></select>; default: return <input disabled type={field.type === "NUMBER" ? "number" : field.type === "DATE" ? "date" : field.type === "TIME" ? "time" : "text"} placeholder={label} />; } })();
  return <article className={`builder-field-card field-type-${field.type.toLowerCase()} span-${width} ${dragging ? "dragging" : ""}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onDrop(); }}>
    <div className="builder-field-heading"><label className="builder-preview-label"><input required aria-label="Field label" placeholder="Enter field label" value={field.label} onChange={(event) => onChange({ label: event.target.value })} />{field.required && <i aria-hidden="true">*</i>}</label><div className="builder-field-toolbar"><button type="button" className="field-drag-handle" draggable aria-label={`Drag ${label} to reposition`} title="Drag to reposition" onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; onDragStart(); }}><FieldActionIcon name="drag" /></button><details className="field-settings"><summary aria-label={`Edit ${label}`} title="Edit field"><FieldActionIcon name="edit" /></summary><div className="field-settings-panel"><label><span>Input type</span><select aria-label="Field type" value={field.type} onChange={(event) => onChange({ type: event.target.value as FieldType, height: undefined })}>{fieldTypes.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select></label><label className="required-toggle"><input type="checkbox" checked={field.required} onChange={(event) => onChange({ required: event.target.checked })} /> Required field</label>{choicesEditor}<span className="field-size-readout">Size: {width}/6 width · auto height</span><div className="field-settings-actions"><button type="button" disabled={index === 0} onClick={() => onMove(-1)}>Move earlier</button><button type="button" disabled={index === count - 1} onClick={() => onMove(1)}>Move later</button></div></div></details><button type="button" className="field-delete-button" aria-label={`Delete ${label}`} title="Delete field" onClick={onRemove}>×</button></div></div>
    <div className="builder-output-preview" aria-label={`Preview of ${label}`}>{preview}</div>
    <button type="button" className="field-resize-width" aria-label={`Drag to resize ${label} width`} onPointerDown={beginResize} />
  </article>;
}

export default function TemplateBuilderPage({ user, createMode = false, editMode = false }: { user: User; createMode?: boolean; editMode?: boolean }) {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { templateId } = useParams();
  const [items, setItems] = useState(read); const pageTemplate = editMode ? items.find((item) => item.id === templateId) : undefined;
  const [kind, setKind] = useState<Kind>(() => pageTemplate?.kind ?? (searchParams.get("kind") === "CHILD" ? "CHILD" : "PARENT")); const [query, setQuery] = useState(""); const [adding, setAdding] = useState(false);
  const [sections, setSections] = useState<Section[]>(() => pageTemplate?.sections ? structuredClone(pageTemplate.sections) : [newSection()]);
  const [form, setForm] = useState(() => ({ name: pageTemplate?.name ?? "", code: pageTemplate?.code ?? "", description: pageTemplate?.description ?? "", active: pageTemplate?.active ?? true }));
  const [viewing, setViewing] = useState<Template>();
  const [editing, setEditing] = useState<Template>();
  const [editForm, setEditForm] = useState({ name: "", code: "", description: "" });
  const [draggedField, setDraggedField] = useState<{ sectionId: string; fieldId: string }>();
  const [activeBuilderTabs, setActiveBuilderTabs] = useState<Record<string, string>>({});
  const [visibleInstructions, setVisibleInstructions] = useState<Record<string, boolean>>({});
  const [visiblePermissions, setVisiblePermissions] = useState<Record<string, boolean>>({});
  if (!["SUPER_ADMIN", "USER_ADMIN"].includes(user.role)) return <Navigate to="/dashboard" replace />;
  const visible = items.filter((item) => item.kind === kind && `${item.name} ${item.code} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  const save = (next: Template[]) => { setItems(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const updateSection = (id: string, change: Partial<Section>) => setSections(sections.map((section) => section.id === id ? { ...section, ...change } : section));
  const updateField = (sectionId: string, fieldId: string, change: Partial<Field>) => setSections(sections.map((section) => section.id === sectionId ? { ...section, fields: section.fields.map((field) => field.id === fieldId ? { ...field, ...change } : field) } : section));
  const moveField = (sectionId: string, fieldIndex: number, direction: -1 | 1) => setSections(sections.map((section) => { if (section.id !== sectionId) return section; const target = fieldIndex + direction; if (target < 0 || target >= section.fields.length) return section; const fields = [...section.fields]; [fields[fieldIndex], fields[target]] = [fields[target], fields[fieldIndex]]; return { ...section, fields }; }));
  const dropField = (sectionId: string, targetId: string) => { if (!draggedField || draggedField.sectionId !== sectionId || draggedField.fieldId === targetId) return; setSections(sections.map((section) => { if (section.id !== sectionId) return section; const fields = [...section.fields]; const from = fields.findIndex((field) => field.id === draggedField.fieldId); const to = fields.findIndex((field) => field.id === targetId); if (from < 0 || to < 0) return section; const [moved] = fields.splice(from, 1); fields.splice(to, 0, moved); return { ...section, fields }; })); setDraggedField(undefined); };
  const addTab = (section: Section) => { const id = crypto.randomUUID(); const firstTab = section.tabs?.length ? undefined : { id: crypto.randomUUID(), label: "Tab 1" }; const tabs = [...(firstTab ? [firstTab] : section.tabs ?? []), { id, label: `Tab ${(section.tabs?.length ?? 0) + (firstTab ? 2 : 1)}` }]; const fields = firstTab ? section.fields.map((field) => ({ ...field, tabId: firstTab.id })) : section.fields; updateSection(section.id, { tabs, fields }); setActiveBuilderTabs({ ...activeBuilderTabs, [section.id]: id }); };
  const removeTab = (section: Section, tabId: string) => { const tabs = section.tabs?.filter((tab) => tab.id !== tabId) ?? []; const fallback = tabs[0]?.id; updateSection(section.id, { tabs: tabs.length ? tabs : undefined, fields: section.fields.map((field) => field.tabId === tabId ? { ...field, tabId: fallback } : field) }); setActiveBuilderTabs({ ...activeBuilderTabs, [section.id]: fallback ?? "" }); };
  const createTemplate = (draft: boolean) => { if (!form.name.trim() || !form.code.trim() || !form.description.trim()) return; const details = { name: form.name.trim(), code: form.code.trim().toUpperCase(), description: form.description.trim(), sections, updatedAt: new Date().toISOString() }; const next = editMode && pageTemplate ? items.map((item) => item.id === pageTemplate.id ? { ...item, ...details, active: form.active, draft: false } : item) : [{ id: crypto.randomUUID(), kind, ...details, discipline: DISCIPLINES[0], active: draft ? false : form.active, draft }, ...items]; localStorage.setItem(storageKey, JSON.stringify(next)); navigate(`/settings/templates?kind=${kind}`); };
  const submit = (event: FormEvent) => { event.preventDefault(); createTemplate(false); };
  const changeKind = (next: Kind) => { setKind(next); setAdding(false); };
  const startEdit = (template: Template) => { setEditing(template); setEditForm({ name: template.name, code: template.code, description: template.description }); };
  const submitEdit = (event: FormEvent) => { event.preventDefault(); if (!editing || !editForm.name.trim() || !editForm.code.trim() || !editForm.description.trim()) return; save(items.map((item) => item.id === editing.id ? { ...item, name: editForm.name.trim(), code: editForm.code.trim().toUpperCase(), description: editForm.description.trim(), updatedAt: new Date().toISOString() } : item)); setEditing(undefined); };
  const remove = (template: Template) => { if (window.confirm(`Delete ${template.name}? This cannot be undone.`)) save(items.filter((item) => item.id !== template.id)); };

  const renderBuilderSection = (section: Section, sectionIndex: number) => { const activeTabId = activeBuilderTabs[section.id] || section.tabs?.[0]?.id; const visibleFields = section.tabs?.length ? section.fields.filter((field) => field.tabId === activeTabId) : section.fields; const instructionsVisible = visibleInstructions[section.id] ?? Boolean(section.description); return <section className="builder-section" key={section.id}>
    <div className="builder-section-head"><b>{sectionIndex + 1}</b><input required aria-label={`Section ${sectionIndex + 1} title`} value={section.title} onChange={(event) => updateSection(section.id, { title: event.target.value })} /><div className="builder-section-actions"><button type="button" className="section-header-action" aria-expanded={Boolean(visiblePermissions[section.id])} aria-controls={`section-permissions-${section.id}`} title={`${section.editAccess?.assessor ? "Assigned Assessor" : "No Assessor"} · ${section.editAccess?.mtGroupIds?.length ?? 0} MT groups`} onClick={() => setVisiblePermissions({ ...visiblePermissions, [section.id]: !visiblePermissions[section.id] })}>Edit permissions</button><button type="button" className="toggle-section-instructions" aria-expanded={instructionsVisible} onClick={() => setVisibleInstructions({ ...visibleInstructions, [section.id]: !instructionsVisible })}>{instructionsVisible ? "Hide instructions" : "+ Instructions"}</button><button type="button" className="add-section-tab" onClick={() => addTab(section)}>+ Add tab</button></div><button type="button" disabled={sections.length === 1} onClick={() => setSections(sections.filter((item) => item.id !== section.id))}>×</button></div>
    <SectionPermissionSummary access={section.editAccess} />
    {visiblePermissions[section.id] && <div className="section-edit-access" id={`section-permissions-${section.id}`}><div><label><input type="checkbox" checked={section.editAccess?.assessor ?? false} onChange={(event) => updateSection(section.id, { editAccess: { ...section.editAccess, assessor: event.target.checked } })} />Allow assigned Assessor to edit this section</label><p>Allow members of these assigned MT groups to edit this section:</p>{readGroups().map((group) => <label key={group.id}><input type="checkbox" checked={section.editAccess?.mtGroupIds?.includes(group.id) ?? false} onChange={(event) => updateSection(section.id, { editAccess: { ...section.editAccess, mtGroupIds: event.target.checked ? [...(section.editAccess?.mtGroupIds ?? []), group.id] : section.editAccess?.mtGroupIds?.filter((id) => id !== group.id) } })} />{group.name}</label>)}</div></div>}
    {instructionsVisible && <input className="section-description" autoFocus={!section.description} aria-label={`Section ${sectionIndex + 1} instructions`} placeholder="Section instructions (optional)" value={section.description} onChange={(event) => updateSection(section.id, { description: event.target.value })} />}
    {section.tabs?.length ? <div className="builder-section-tabs" role="tablist" aria-label={`${section.title} tabs`}>{section.tabs.map((tab, tabIndex) => <div className={tab.id === activeTabId ? "active" : ""} key={tab.id}><button type="button" role="tab" aria-selected={tab.id === activeTabId} onClick={() => setActiveBuilderTabs({ ...activeBuilderTabs, [section.id]: tab.id })}><b>{String.fromCharCode(65 + tabIndex)}</b><input aria-label={`Tab ${tabIndex + 1} name`} value={tab.label} onClick={(event) => event.stopPropagation()} onChange={(event) => updateSection(section.id, { tabs: section.tabs?.map((item) => item.id === tab.id ? { ...item, label: event.target.value } : item) })} /></button><button type="button" aria-label={`Remove tab ${tabIndex + 1}`} onClick={() => removeTab(section, tab.id)}>×</button></div>)}</div> : null}
    <div className="builder-fields builder-layout-canvas">{visibleFields.map((field, index) => <BuilderFieldCard key={field.id} field={field} childTemplates={items.filter((item) => item.kind === "CHILD")} index={index} count={visibleFields.length} dragging={draggedField?.fieldId === field.id} onChange={(change) => updateField(section.id, field.id, change)} onMove={(direction) => { const actualIndex = section.fields.findIndex((item) => item.id === field.id); moveField(section.id, actualIndex, direction); }} onRemove={() => updateSection(section.id, { fields: section.fields.filter((item) => item.id !== field.id) })} onDragStart={() => setDraggedField({ sectionId: section.id, fieldId: field.id })} onDrop={() => dropField(section.id, field.id)} />)}</div>
    <button type="button" className="add-field-button" onClick={() => updateSection(section.id, { fields: [...section.fields, { id: crypto.randomUUID(), label: "", type: "TEXT", required: false, width: 3, tabId: activeTabId }] })}>+ Add form element</button>
  </section>; };

  const editor = <form className="template-builder-form template-builder-page-form" onSubmit={submit}>
    <div className="builder-title template-details-title"><div><h3>Template Details</h3><p>Define the template name, code, and purpose.</p></div></div>
    <div className="builder-meta builder-meta-row"><label>Template name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Template code<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label>Description<input required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="template-active-switch">Status<span><input type="checkbox" aria-label="Active template" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /><i aria-hidden="true" /><b>{form.active ? "Active" : "Inactive"}</b></span></label></div>
    <div className="builder-title"><div><h3>Form sections</h3><p>Each section becomes a step when this template is selected.</p></div><button type="button" className="button ghost small" onClick={() => setSections([...sections, newSection()])}>+ Add section</button></div>
        {sections.map(renderBuilderSection)}
    <div className="builder-actions"><Link className="button ghost" to={`/settings/templates?kind=${kind}`}>Cancel</Link>{!editMode && <button type="button" className="button ghost" onClick={() => createTemplate(true)}>Save as draft</button>}<button className="button primary">{editMode ? "Save changes" : `Create ${kind === "PARENT" ? "parent" : "child"} template`}</button></div>
  </form>;

  if (editMode && !pageTemplate) return <Navigate to="/settings/templates" replace />;
  if (createMode || editMode) return <div className="page template-page template-create-page"><header className="page-header"><div><span className="eyebrow">System management</span><h1>{editMode ? "Edit" : "Create"} {kind === "PARENT" ? "parent" : "child"} template</h1><p>{editMode ? "Update the template details and form sections used when raising a permit." : "Build the reusable sections and elements users complete when raising a permit."}</p></div></header><section className="card">{editor}</section></div>;

  return <div className="page template-page">
    <header className="page-header"><div><span className="eyebrow">System management</span><h1>Permit templates</h1><p>Create reusable permit forms with configurable sections and elements.</p></div><button className="button primary" onClick={() => navigate(`/settings/templates/new?kind=${kind}`)}>+ Add {kind === "PARENT" ? "parent" : "child"} template</button></header>
    <section className="card template-workspace">
      <div className="template-tabs" role="tablist" aria-label="Template types"><button role="tab" aria-selected={kind === "PARENT"} className={kind === "PARENT" ? "active" : ""} onClick={() => changeKind("PARENT")}>Parent Template <b>{items.filter((item) => item.kind === "PARENT").length}</b></button><button role="tab" aria-selected={kind === "CHILD"} className={kind === "CHILD" ? "active" : ""} onClick={() => changeKind("CHILD")}>Child Template <b>{items.filter((item) => item.kind === "CHILD").length}</b></button></div>
      <div className="template-toolbar"><label className="search"><span>⌕</span><input aria-label="Search templates" placeholder="Search template name, code or description" value={query} onChange={(event) => setQuery(event.target.value)} /></label><span className="result-count">{visible.length} templates</span></div>
      {adding && <form className="template-builder-form" onSubmit={submit}>
        <div className="builder-title template-details-title"><div><h3>Template Details</h3><p>Define the template name, code, and purpose.</p></div></div>
        <div className="builder-meta builder-meta-row"><label>Template name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Template code<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label>Description<input required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="template-active-switch">Status<span><input type="checkbox" aria-label="Active template" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /><i aria-hidden="true" /><b>{form.active ? "Active" : "Inactive"}</b></span></label></div>
        <div className="builder-title"><div><h3>Form sections</h3><p>Build the fields users complete when this template is selected.</p></div><button type="button" className="button ghost small" onClick={() => setSections([...sections, newSection()])}>+ Add section</button></div>
        {sections.map((section, sectionIndex) => <section className="builder-section" key={section.id}><div className="builder-section-head"><b>{sectionIndex + 1}</b><input required aria-label={`Section ${sectionIndex + 1} title`} value={section.title} onChange={(event) => updateSection(section.id, { title: event.target.value })} /><button type="button" disabled={sections.length === 1} onClick={() => setSections(sections.filter((item) => item.id !== section.id))}>×</button></div><input className="section-description" placeholder="Section instructions (optional)" value={section.description} onChange={(event) => updateSection(section.id, { description: event.target.value })} /><div className="builder-fields">{section.fields.map((field, index) => <div className="builder-field" key={field.id}><span>{index + 1}</span><input required aria-label="Field label" placeholder="Field label" value={field.label} onChange={(event) => updateField(section.id, field.id, { label: event.target.value })} /><select aria-label="Field type" value={field.type} onChange={(event) => updateField(section.id, field.id, { type: event.target.value as FieldType })}>{[["TEXT", "Short text"], ["TEXTAREA", "Long text"], ["NUMBER", "Number"], ["DATE", "Date"], ["CHECKBOX", "Checkbox"], ["SELECT", "Dropdown"]].map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select>{field.type === "SELECT" && <input aria-label="Dropdown choices" placeholder="Choices separated by commas" value={field.options?.join(", ") ?? ""} onChange={(event) => updateField(section.id, field.id, { options: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} />}<label className="required-toggle"><input type="checkbox" checked={field.required} onChange={(event) => updateField(section.id, field.id, { required: event.target.checked })} /> Required</label><button type="button" onClick={() => updateSection(section.id, { fields: section.fields.filter((item) => item.id !== field.id) })}>×</button></div>)}</div><button type="button" className="add-field-button" onClick={() => updateSection(section.id, { fields: [...section.fields, { id: crypto.randomUUID(), label: "", type: "TEXT", required: false }] })}>+ Add form element</button></section>)}
        <div className="builder-actions"><button type="button" className="button ghost" onClick={() => setAdding(false)}>Cancel</button><button className="button primary">Create {kind === "PARENT" ? "parent" : "child"} template</button></div>
      </form>}
      <table className="template-table"><thead><tr><th>Permit code</th><th>Template name</th><th>Description</th><th>Form</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map((template) => <tr key={template.id}><td><div className={`template-kind-icon ${template.kind.toLowerCase()}`}>{template.code}</div></td><td><strong>{template.name}</strong></td><td>{template.description}</td><td>{template.sections?.length ?? 0} sections<br /><small>{template.sections?.reduce((count, section) => count + section.fields.length, 0) ?? 0} elements</small></td><td><button type="button" className={`template-status ${template.active ? "enabled" : ""} ${template.draft ? "draft" : ""}`} aria-label={`Set ${template.name} ${template.active ? "inactive" : "active"}`} onClick={() => save(items.map((item) => item.id === template.id ? { ...item, active: !item.active, draft: false } : item))}>{template.draft ? "Draft" : template.active ? "Active" : "Inactive"}</button></td><td><div className="template-row-actions"><button type="button" aria-label="View" title="View" onClick={() => setViewing(template)}><TemplateActionIcon name="view" /></button><button type="button" aria-label="Edit" title="Edit" onClick={() => navigate(`/settings/templates/${template.id}/edit`)}><TemplateActionIcon name="edit" /></button><button type="button" className="danger" aria-label="Delete" title="Delete" onClick={() => remove(template)}><TemplateActionIcon name="delete" /></button></div></td></tr>)}</tbody></table>
    </section>
    {viewing && <div className="admin-modal-backdrop" onMouseDown={() => setViewing(undefined)}><section className="admin-modal template-detail-modal" role="dialog" aria-modal="true" aria-label={`View ${viewing.name}`} onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setViewing(undefined)} aria-label="Close">×</button><header className="template-detail-header"><span className={`template-kind-icon ${viewing.kind.toLowerCase()}`}>{viewing.code}</span><div><h2>{viewing.name}</h2><p>{viewing.description}</p></div><span className={`template-status template-status-badge ${viewing.active ? "enabled" : ""} ${viewing.draft ? "draft" : ""}`}>{viewing.draft ? "Draft" : viewing.active ? "Active" : "Inactive"}</span></header><div className="template-modal-sections"><h3>Form sections</h3>{viewing.sections?.length ? viewing.sections.map((section, sectionIndex) => <article key={section.id}><header><b>{sectionIndex + 1}</b><div><strong>{section.title}</strong><span>{section.description || "No section instructions"}</span></div></header>{section.fields.length ? <ul>{section.fields.map((field, fieldIndex) => <li key={field.id}><b>{fieldIndex + 1}</b><div><strong>{field.label}</strong><span>{field.type === "TEXT" ? "Short text" : field.type === "TEXTAREA" ? "Long text" : field.type === "SELECT" ? "Dropdown" : field.type.charAt(0) + field.type.slice(1).toLowerCase()}{field.required ? " · Required" : " · Optional"}</span>{field.type === "SELECT" && field.options?.length ? <small>Choices: {field.options.join(", ")}</small> : null}</div></li>)}</ul> : <p>No form elements configured.</p>}</article>) : <p className="template-empty-sections">No form sections configured.</p>}</div></section></div>}
    {editing && <div className="admin-modal-backdrop" onMouseDown={() => setEditing(undefined)}><form className="admin-modal template-edit-modal" role="dialog" aria-modal="true" aria-label={`Edit ${editing.name}`} onMouseDown={(event) => event.stopPropagation()} onSubmit={submitEdit}><button type="button" className="modal-close" onClick={() => setEditing(undefined)} aria-label="Close">×</button><h2>Edit template</h2><div className="template-edit-fields"><label>Template name<input aria-label="Edit template name" required value={editForm.name} onChange={(event) => setEditForm({ ...editForm, name: event.target.value })} /></label><label>Reference code<input aria-label="Edit reference code" required value={editForm.code} onChange={(event) => setEditForm({ ...editForm, code: event.target.value })} /></label><label>Description<textarea aria-label="Edit description" required rows={4} value={editForm.description} onChange={(event) => setEditForm({ ...editForm, description: event.target.value })} /></label></div><div className="builder-actions"><button type="button" className="button ghost" onClick={() => setEditing(undefined)}>Cancel</button><button className="button primary">Save changes</button></div></form></div>}
  </div>;
}
